version: "3.9"
# docker run -p 8080:8080 -p 50000:50000 -v "$PWD/jenkins_home:/var/jenkins_home" jenkins/jenkins:lts
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: jenkins
    container_name: jenkins
    environment:
      - TZ=America/Denver
    volumes:
      - $HOME/jenkins:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000