version: "3.9"
# alternativlely run: docker run -p 8080:8080 -p 50000:50000 -v "$PWD/jenkins_home:/var/jenkins_home" jenkins/jenkins:lts
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: jenkins
    container_name: jenkins
    environment:
      - TZ=America/Denver
    volumes:
      - $HOME/jenkins:/var/jenkins_home #volume mapping to save jenkins configuration
    ports:
      - 8080:8080 # port for access to Jenkins Console
      - 50000:50000 # port for JNLP connection from Jenkins Agent to the Jenkins Controller